"""Write the frozen, visible output for Project 1 so a grader can read results without running code.

Runs fully offline on the bundled seed data (no live SEC/market calls) with a FIXED valuation date,
so the same command always reproduces the same numbers.

    python export_visible_output.py

Writes:
    output/visible_output.json   - headline numbers, scenarios, checks, inputs, as-of dates
    output/visible_output.md     - the same results as readable tables
    output/TSLA_model.xlsx       - full workbook (sources, assumptions, statements, valuation, checks)
"""
from __future__ import annotations

import json
from datetime import date
from pathlib import Path

import numpy as np
import pandas as pd

from tsla_model import config
from tsla_model.assumptions import default_assumptions
from tsla_model.data_ingestion import build_source_table, get_data, historical_table
from tsla_model.excel_export import build_workbook
from tsla_model.scenarios import full_analysis

VALUATION_DATE = date(2026, 9, 24)   # matches seed market data as-of date
SCENARIO = "base"
OUT = Path(__file__).parent / "output"


def _clean(x):
    if isinstance(x, (np.floating, float)):
        return None if np.isnan(x) else round(float(x), 4)
    if isinstance(x, (np.integer,)):
        return int(x)
    return x


def _records(df: pd.DataFrame) -> list[dict]:
    return [{k: _clean(v) for k, v in row.items()} for row in df.to_dict(orient="records")]


def main() -> None:
    OUT.mkdir(exist_ok=True)
    b = get_data(live=False)
    a = default_assumptions(b)
    x = full_analysis(b, a, SCENARIO, VALUATION_DATE)
    ev = x["evals"][SCENARIO]
    v = ev.valuation
    checks = v.checks if not v.checks.empty else pd.DataFrame()

    summary = {
        "target": "Tesla, Inc. (TSLA)",
        "valuation_date": VALUATION_DATE.isoformat(),
        "currency_units": "USD millions except per-share",
        "data_mode": "offline seed data (tsla_model/data/seed_*.json)",
        "price": {k: b.market["price"].get(k) for k in ("value", "as_of", "source")},
        "risk_free": {k: b.market["risk_free"].get(k) for k in ("value", "as_of", "source")},
        "cash_flow_convention": "FCFE (free cash flow to equity), discounted at cost of equity",
        "base_case": {
            "status": v.status,
            "value_per_share": _clean(v.value_per_share),
            "upside_vs_price": _clean(v.upside),
            "cost_of_equity": _clean(v.ke),
            "terminal_growth": _clean(v.g),
            "terminal_value_share_of_dcf": _clean(v.tv_share_of_dcf),
            "diluted_shares_m": _clean(v.shares),
            "failures": v.failures,
            "warnings": v.warnings,
        },
        "scenarios": _records(x["summary"]),
        "market_implied_what_must_be_true": _records(x["wmbt"]) if "wmbt" in x else [],
        "tornado_one_at_a_time": _records(x["tornado"]) if "tornado" in x else [],
        "checks_all_pass": bool(v.status == "OK"),
    }
    (OUT / "visible_output.json").write_text(json.dumps(summary, indent=2, default=str))

    md = [
        "# Visible output - Tesla (TSLA) pro-forma valuation",
        "",
        f"Generated by `python export_visible_output.py` (offline seed data, valuation date "
        f"{VALUATION_DATE.isoformat()}). USD millions except per-share.",
        "",
        f"- Market price: ${b.market['price']['value']:.2f} (as of {b.market['price']['as_of']})",
        f"- Base-case value per share: **${v.value_per_share:,.2f}** ({v.upside:+.0%} vs. price)"
        if v.status == "OK" else f"- Base case status: {v.status}",
        f"- Cost of equity {v.ke:.2%}; terminal growth {v.g:.2%}; terminal value = {v.tv_share_of_dcf:.0%} of DCF value",
        f"- Integrity checks: {'all pass' if v.status == 'OK' else 'FAILED - valuation blocked'}",
        "",
        "## Scenarios",
        "",
        x["summary"].to_markdown(index=False, floatfmt=",.4g"),
    ]
    if "wmbt" in x:
        md += ["", "## What the market price requires (each on its own)", "", x["wmbt"].to_markdown(index=False)]
    if "tornado" in x:
        md += ["", "## One-at-a-time sensitivity (tornado)", "", x["tornado"].to_markdown(index=False, floatfmt=",.4g")]
    if not v.equity_bridge.empty:
        md += ["", "## Equity bridge", "", v.equity_bridge.to_markdown(index=False, floatfmt=",.2f")]
    (OUT / "visible_output.md").write_text("\n".join(md) + "\n")

    xlsx = build_workbook(b, a, SCENARIO, x["evals"], x, build_source_table(b), historical_table(b))
    (OUT / "TSLA_model.xlsx").write_bytes(xlsx)
    print(f"Base value/share: {v.value_per_share:.2f}  status={v.status}  -> wrote {OUT}")


if __name__ == "__main__":
    main()
